// Evan Borden — site content & skills data
window.SITE_DATA = {
  name: "Evan Borden",
  role: "Manager, Engineering",
  company: "Razorfish",
  location: "Charlotte, NC",
  tz: "America/New_York",
  email: "evanpatrickborden@outlook.com",
  phone: "704.401.4864",
  linkedin: "https://www.linkedin.com/in/evan-borden/",
  tagline: "Hands-on engineering leader. Ships software, mentors people, ports DOOM into Unity for fun.",
  manifesto: "Eighteen years writing code, six leading the people who write it. I move comfortably from frontend to backend to infrastructure — designing systems, debugging the gnarly stuff, and shipping the work end to end. I mentor engineers, translate between technical and business, and I'm still curious enough to spend my weekends on a personal Linux box wiring up new tools just to see how they work. The job is to make the team faster, the codebase calmer, and the client confident — in roughly that order.",

  experience: [
    {
      role: "Manager, Engineering",
      company: "Razorfish",
      period: "Nov 2018 — Present",
      length: "7+ yrs",
      tag: "current",
      bullets: [
        "Led front- and back-end teams across multi-year client engagements — Disney Rewards, UC Health, Labcorp — driving user engagement, revenue growth and YoY retention.",
        "Stood up CI/CD on Azure DevOps and GitLab; cut deployment time by more than half.",
        "Architected integrations with Chase Bank, Adobe CJA, Adobe Target and Shoppable on top of WordPress and AEM stacks.",
        "Mentored junior devs through code review, standards work and architecture pairing.",
        "Translated technical decisions into language clients and PMs could act on.",
      ],
    },
    {
      role: "Senior Web Developer",
      company: "Interactive Knowledge",
      period: "Sep 2012 — Oct 2018",
      length: "6 yrs",
      tag: "",
      bullets: [
        "Built media-rich interactive experiences for non-profits, museums and educational institutions.",
        "Shipped responsive, mobile-first apps in React and Vue against custom REST and microservice backends.",
        "Partnered with UX to translate design comps into accessible, performant interfaces.",
      ],
    },
    {
      role: "Front-End Web Developer",
      company: "Lowe's Companies, Inc.",
      period: "2012",
      length: "1 yr",
      tag: "",
      bullets: [
        "Contributed to the e-commerce platform behind Lowes.com.",
        "Built and maintained brand sites; ran audits and performance work that improved speed and SEO.",
      ],
    },
    {
      role: "Junior Web Developer",
      company: "Cedar Management Group",
      period: "May 2008 — Jul 2010",
      length: "2 yrs",
      tag: "first job",
      bullets: [
        "Custom WordPress themes and plugins tailored to client needs.",
        "Integrated CMSes so non-technical clients could run their own content.",
      ],
    },
  ],

  education: [
    { school: "UNC Charlotte", degree: "B.S. Computer Science — Software Engineering Concentration", years: "2006 — 2008" },
    { school: "Central Piedmont Community College", degree: "A.A.S. Advertising + Graphic Design", years: "2004 — 2006" },
  ],

  // Parsed from skills.xlsx — categories, skill, rating 1-4, last used, evidence
  skills: [
    { cat: "Cloud & Infrastructure", skill: "AWS", rating: 3, year: 2026, notes: "Personal projects (multi-year) — VM (EC2) provisioning, security groups, networking, DNS / Route 53, domain management, cost monitoring." },
    { cat: "Cloud & Infrastructure", skill: "Azure", rating: 3, year: 2026, notes: "Personal projects (multi-year) — VM provisioning, network security groups, DNS, domain management, cost analysis." },
    { cat: "Cloud & Infrastructure", skill: "Docker", rating: 3, year: 2026, notes: "Disney Rewards local environment running WordPress; comfortable with commands, configs, and compose flows." },
    { cat: "Cloud & Infrastructure", skill: "Linux Server Administration", rating: 4, year: 2026, notes: "Personal projects (multi-year) — SSH, Apache and Nginx, filesystem permissions, user/group management, service configuration. Also recommended optimization for UC Health on-prem AEM." },
    { cat: "CMS / DAM", skill: "WordPress", rating: 4, year: 2026, notes: "Disney Rewards — custom theme & plugins; REST API extension, hooks/filters, custom post types and taxonomies, WP-CLI, sanitization patterns." },
    { cat: "CMS / DAM", skill: "Adobe Experience Manager (AEM)", rating: 3, year: 2023, notes: "UC Health — multi-module Maven project. OSGi services, Sling models and servlets, HTL templating, JCR content packaging, Touch UI dialogs." },
    { cat: "CMS / DAM", skill: "Gutenberg / Block Editor", rating: 3, year: 2026, notes: "Disney Rewards — block.json, @wordpress/scripts, Interactivity API." },
    { cat: "CMS / DAM", skill: "ACF Pro", rating: 4, year: 2025, notes: "Disney Rewards — field groups, options pages, ACF blocks." },
    { cat: "Frontend", skill: "React", rating: 3, year: 2026, notes: "Disney Rewards — Gutenberg block editor; hobby projects and experiments." },
    { cat: "Frontend", skill: "Vue.js", rating: 3, year: 2023, notes: "UC Health — Vue 2 in AEM clientlibs; Vue 3 experimentation across projects." },
    { cat: "Frontend", skill: "Node.js", rating: 3, year: 2026, notes: "Disney Rewards and UC Health — front-end build tooling runtime." },
    { cat: "Frontend", skill: "Sass / SCSS", rating: 4, year: 2026, notes: "Disney Rewards and UC Health — theme and clientlib styles." },
    { cat: "Backend", skill: "PHP", rating: 4, year: 2026, notes: "Disney Rewards & non-professional projects — PHP 8.2, strict types, PSR-12." },
    { cat: "Backend", skill: "Java", rating: 3, year: 2023, notes: "UC Health — OSGi components, Sling Models, servlets." },
    { cat: "Backend", skill: "REST API Design", rating: 3, year: 2023, notes: "UC Health — Sling servlet JSON endpoints." },
    { cat: "Backend", skill: "MySQL / SQL", rating: 3, year: 2026, notes: "Disney Rewards — custom WP tables, prepared statements via $wpdb, schema design. Comfortable with MySQL/MariaDB tooling." },
    { cat: "Backend", skill: "Composer", rating: 4, year: 2026, notes: "Disney Rewards — PHP dependency management." },
    { cat: "DevOps & Tooling", skill: "Webpack", rating: 3, year: 2026, notes: "Disney Rewards and UC Health — custom multi-config builds." },
    { cat: "DevOps & Tooling", skill: "Git & Deployment Workflows", rating: 3, year: 2026, notes: "Branching strategies, merge/pull requests, code review, deploying through dev / stage / prod pipelines." },
    { cat: "DevOps & Tooling", skill: "CI/CD Pipelines", rating: 2, year: 2026, notes: "Disney Rewards — ship through GitLab CI/CD; can use and extend existing pipelines." },
    { cat: "DevOps & Tooling", skill: "Postman", rating: 3, year: 2023, notes: "UC Health — API collections for Sling servlets." },
    { cat: "Data & Analytics", skill: "Adobe Analytics", rating: 3, year: 2026, notes: "Disney Rewards (with CJA) and UC Health — Adobe Analytics tagging and data layer via Adobe Launch." },
    { cat: "CDP & Personalization", skill: "Adobe Target", rating: 3, year: 2026, notes: "Disney Rewards and UC Health — at.js anti-flicker, mbox tracking." },
    { cat: "AI & Machine Learning", skill: "Prompt Engineering", rating: 2, year: 2026, notes: "Personal use of local AI tooling (LM Studio and similar) for experimentation; no production AI integrations." },
    { cat: "AI & Machine Learning", skill: "LLM Integration", rating: 3, year: 2026, notes: "Personal hobby — Linux server with custom Nginx, MCP and GitHub webhook integration to Claude apps to power prompt-driven website creation, automated code management, WP REST API publishing." },
    { cat: "Testing & QA", skill: "Accessibility Testing (WCAG)", rating: 3, year: 2026, notes: "Disney Rewards (consumer) and UC Health (healthcare) — accessible markup." },
    { cat: "Security & Compliance", skill: "OAuth / OIDC", rating: 3, year: 2026, notes: "Disney Rewards — Chase API token lifecycle in the Chase WP Connect plugin." },
    { cat: "Security & Compliance", skill: "JWT / JOSE", rating: 4, year: 2026, notes: "Disney Rewards — JWS/JWE with web-token/jwt-framework and phpseclib3." },
    { cat: "Architecture", skill: "Agile / SAFe", rating: 3, year: 2026, notes: "Disney Rewards and UC Health — Jira/Azure DevOps, merge requests, release branches." },
    { cat: "Architecture", skill: "System Design", rating: 3, year: 2026, notes: "Disney Rewards, UC Health and Labcorp — architecture analysis, research, and proposals at the application and integration layer." },
    { cat: "Architecture", skill: "Technical Analysis & Documentation", rating: 4, year: 2026, notes: "Architecture analysis and research, technical strategy, diagrams and flowcharts, technical documentation." },
    { cat: "Healthcare", skill: "Epic EHR", rating: 2, year: 2023, notes: "UC Health — managed the integration; architecture-level familiarity." },
    { cat: "Game Dev / Hobby", skill: "C#", rating: 3, year: 2026, notes: "Personal Unity 3D game development — primary scripting language for multi-year hobby projects." },
    { cat: "Game Dev / Hobby", skill: "Unity 3D", rating: 3, year: 2026, notes: "Personal hobby — built a DOOM-style first-person shooter and other experiments; component scripting, scenes, prefabs, physics, input." },
    { cat: "Game Dev / Hobby", skill: "Game Design", rating: 2, year: 2026, notes: "Personal Unity 3D projects — game concepts, level and environment design, in-game interface design." },
  ],

  projects: [
    {
      title: "Claude × MCP × WordPress",
      kind: "Personal · 2025–26",
      blurb: "A self-hosted Linux box running custom Nginx that wires GitHub webhooks and the Model Context Protocol up to Claude apps. The result: prompt-driven WordPress page creation, automated code management, and CMS publishing that I drive from chat.",
      stack: ["Linux", "Nginx", "MCP", "WordPress REST", "GitHub Webhooks"],
    },
    {
      title: "Unity DOOM-style FPS",
      kind: "Personal · multi-year",
      blurb: "A first-person shooter built in Unity as a long-running side project. Component scripts in C#, hand-built scenes and prefabs, physics, input, level and environment design — the whole stack, just for the love of it.",
      stack: ["Unity 3D", "C#", "Game Design"],
    },
    {
      title: "Disney Rewards",
      kind: "Razorfish · 2019–present",
      blurb: "Custom WordPress platform with bespoke Gutenberg blocks, ACF Pro field architecture, Chase Bank API integration via JWT/JOSE, Adobe Analytics + CJA tagging, and Adobe Target personalization. Shipped through GitLab CI/CD.",
      stack: ["WordPress", "PHP 8", "Gutenberg", "Chase API", "Adobe CJA"],
    },
    {
      title: "UC Health",
      kind: "Razorfish · 2019–2023",
      blurb: "Multi-module AEM (Adobe Experience Manager) project on a Maven build — OSGi services, Sling models and servlets, HTL templating, JCR packaging. Vue 2 in AEM clientlibs. Epic EHR integration architecture.",
      stack: ["AEM", "Java", "Sling", "Vue 2", "Maven"],
    },
  ],
};
